/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.loja.roupas.view;

import br.com.loja.roupas.control.ComponenteTelaApresentacao;
import br.com.loja.roupas.dao.CriarDB;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Marcio, Ludimila e Gustavo
 */
public class FmAbertura extends javax.swing.JFrame {

    private Thread tempo = new ControleTempo();

    /**
     * Método construtor do JFrame que inicializa a dimensão retira as bordas do
     * Jframe e centraliza
     */
    public FmAbertura() {
        //Cria o banco e as tabelas se não existe
         CriarDB.criarBancoDeDados();
        // initComponents();
        Dimension dimensao = Toolkit.getDefaultToolkit().getScreenSize();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocation(0, 0);
        setSize(dimensao);
        setUndecorated(true);
        setBackground(new Color(0, 255, 0, 0));
        setContentPane(new ComponenteTelaApresentacao());
        getContentPane().setBackground(Color.BLACK);//pinta o fundo de preto
        setLayout(new BorderLayout());//centraliza a image
        this.setIconImage(new ImageIcon(getClass().getResource("home.png")).getImage());
        iniciarImagem();
        setVisible(true);

        tempo.start();//Controla o tempo de execução em segundos

    }

    /**
     * Método que recebe a imagem de abertura de apresentação
     */
    private void iniciarImagem() {
        URL url = getClass().getResource("abertura.png");
        Icon icon = new ImageIcon(url);
        this.add(new JLabel(icon), BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) { //"Nimbus"
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmAbertura().setVisible(true);
            }
        });
    }

    /**
     * Método de controle de tempos em que a tela de apresentação ira permanecer
     * ativa
     *
     */
    public class ControleTempo extends Thread {

        int time = 5;

        public void run() {
            while (time-- > 0) {
                try {
                    sleep(500);
                } catch (InterruptedException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            setVisible(false);//close the frame
            FmLogin login = new FmLogin();
            login.setVisible(true);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
