/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.loja.roupas.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Eduardo Marcio
 */
public class FmPrincipalMdi extends javax.swing.JFrame {

    /**
     * Método construtor da clsasse FmPrincipal com conexão com o banco
     */
    public FmPrincipalMdi() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPanePrincipal = new javax.swing.JDesktopPane();
        subMenuListaVendas = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        subMenuCliente = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenu();
        subMenuFuncionario = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        subMenuCadProd = new javax.swing.JMenuItem();
        subMenuListaProdutos = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Roupas");
        setMinimumSize(new java.awt.Dimension(850, 700));

        DesktopPanePrincipal.setBackground(new java.awt.Color(240, 240, 240));

        menuCliente.setText("Clientes");

        subMenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        subMenuCliente.setText("Cadastrar Cliente");
        subMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuClienteActionPerformed(evt);
            }
        });
        menuCliente.add(subMenuCliente);

        subMenuListaVendas.add(menuCliente);

        menuFuncionario.setText("Funcionários");

        subMenuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        subMenuFuncionario.setText("Cadastrar Funcionário");
        subMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(subMenuFuncionario);

        subMenuListaVendas.add(menuFuncionario);

        menuProduto.setText("Produtos");

        subMenuCadProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        subMenuCadProd.setText("Cadastro de Produtos");
        subMenuCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadProdActionPerformed(evt);
            }
        });
        menuProduto.add(subMenuCadProd);

        subMenuListaProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        subMenuListaProdutos.setText("Lista de Produtos e Pedido");
        subMenuListaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuListaProdutosActionPerformed(evt);
            }
        });
        menuProduto.add(subMenuListaProdutos);

        subMenuListaVendas.add(menuProduto);

        menuVenda.setText("Vendas");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Lista de Vendas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuVenda.add(jMenuItem1);

        subMenuListaVendas.add(menuVenda);

        setJMenuBar(subMenuListaVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botão que abre o cadasstro de Clientes
     *
     * @param evt
     */
    /**
     * Botão de Menu cliente para abrir tela de cadastro cliente
     *
     * @param evt
     */
    private void subMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuClienteActionPerformed
        // TODO add your handling code here: 

        InternalFrameCliente internoFrameCliente = new InternalFrameCliente();

        DesktopPanePrincipal.add(internoFrameCliente);
        internoFrameCliente.setVisible(true);
        centraliza(internoFrameCliente);

    }//GEN-LAST:event_subMenuClienteActionPerformed

    /**
     * Botão de Menu funcionário para abrir tela de cadastro funcionário
     *
     * @param evt
     */
    private void subMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuFuncionarioActionPerformed
        // TODO add your handling code here:
        InternalFrameFuncionario internoFuncionario = new InternalFrameFuncionario();

        DesktopPanePrincipal.add(internoFuncionario);
        internoFuncionario.setVisible(true);
        centraliza(internoFuncionario);
    }//GEN-LAST:event_subMenuFuncionarioActionPerformed
    /**
     * Botão de Menu produtos para abrir tela de lista produtos
     *
     * @param evt
     */
    private void subMenuListaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuListaProdutosActionPerformed
        // TODO add your handling code here:
        InternalFrameListaProdutoPedido internoListaProdutos = new InternalFrameListaProdutoPedido();

        DesktopPanePrincipal.add(internoListaProdutos);
        internoListaProdutos.setVisible(true);
        centraliza(internoListaProdutos);

    }//GEN-LAST:event_subMenuListaProdutosActionPerformed
    /**
     * Botão de Menu produtos para abrir tela de cadastro produto
     *
     * @param evt
     */
    private void subMenuCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadProdActionPerformed
        // TODO add your handling code here:
        InternalFrameProdutos internoProdutos = new InternalFrameProdutos();

        DesktopPanePrincipal.add(internoProdutos);
        internoProdutos.setVisible(true);

        centraliza(internoProdutos);

    }//GEN-LAST:event_subMenuCadProdActionPerformed
    /**
     * Botão de Menu vendas para abrir lista de vendas
     *
     * @param evt
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        InternalFrameListarVendas listaVendas = new InternalFrameListarVendas();

        DesktopPanePrincipal.add(listaVendas);
        listaVendas.setVisible(true);
        centraliza(listaVendas);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmPrincipalMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmPrincipalMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmPrincipalMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmPrincipalMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmLogin().setVisible(true);
            }
        });
    }

    /**
     * Método que centraliza s JInternalFrames
     *
     * @param janela
     */
    public void centraliza(JInternalFrame janela) {
        // centraliza no JDesktopPane  
        int larguraDesk = DesktopPanePrincipal.getWidth();
        int alturaDesk = DesktopPanePrincipal.getHeight();
        int larguraIFrame = janela.getWidth();
        int alturaIFrame = janela.getHeight();

        janela.setLocation(larguraDesk / 2 - larguraIFrame / 2, alturaDesk / 2 - alturaIFrame / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPanePrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JMenuItem subMenuCadProd;
    private javax.swing.JMenuItem subMenuCliente;
    private javax.swing.JMenuItem subMenuFuncionario;
    private javax.swing.JMenuItem subMenuListaProdutos;
    private javax.swing.JMenuBar subMenuListaVendas;
    // End of variables declaration//GEN-END:variables

}
