/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.loja.roupas.view;

import br.com.loja.roupas.dao.ConexaoDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Eduardo Marcio
 */
public class InternalFrameListaProdutos extends javax.swing.JInternalFrame {

    private Connection conexao;
    private PreparedStatement stmt;
    private ResultSet rs;

    /**
     * Creates new form InternalFrameListarProdutos
     */
    public InternalFrameListaProdutos() {     
        initComponents();
        this.conexao = ConexaoDao.conexaoDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        produtosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery.getResultList();
        produtosList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ((javax.persistence.Query)null).getResultList();
        produtosList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ((javax.persistence.Query)null).getResultList();
        dblojaPUEntityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("dblojaPU").createEntityManager();
        produtosQuery = java.beans.Beans.isDesignTime() ? null : dblojaPUEntityManager0.createQuery("SELECT p FROM Produtos p");
        produtosList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtosQuery.getResultList();
        jPanelListarProduto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisaProdutosLista = new javax.swing.JTextField();
        btnSairProdutolLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabListaProdutos = new javax.swing.JTable();
        btnPesquisarNomeP = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(750, 480));

        jPanelListarProduto.setBackground(new java.awt.Color(204, 204, 255));
        jPanelListarProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanelListarProduto.setPreferredSize(new java.awt.Dimension(680, 430));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Produto Nome: ");

        txtPesquisaProdutosLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaProdutosListaActionPerformed(evt);
            }
        });

        btnSairProdutolLista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSairProdutolLista.setText("Sair");
        btnSairProdutolLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairProdutolListaActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, produtosList3, tabListaProdutos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marca}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tamanho}"));
        columnBinding.setColumnName("Tamanho");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cor}"));
        columnBinding.setColumnName("Cor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precounitario}"));
        columnBinding.setColumnName("Precounitario");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Descricao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idprodutos}"));
        columnBinding.setColumnName("Idprodutos");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tabListaProdutos);
        if (tabListaProdutos.getColumnModel().getColumnCount() > 0) {
            tabListaProdutos.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        btnPesquisarNomeP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarNomeP.setText("Pesquisar");
        btnPesquisarNomeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarNomePActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarProdutoLayout = new javax.swing.GroupLayout(jPanelListarProduto);
        jPanelListarProduto.setLayout(jPanelListarProdutoLayout);
        jPanelListarProdutoLayout.setHorizontalGroup(
            jPanelListarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaProdutosLista, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnPesquisarNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelListarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSairProdutolLista, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );
        jPanelListarProdutoLayout.setVerticalGroup(
            jPanelListarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarProdutoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanelListarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisaProdutosLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarNomeP))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairProdutolLista)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaProdutosListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaProdutosListaActionPerformed
        // TODO add your handling code here:
        pesquisaProdutoLista();

    }//GEN-LAST:event_txtPesquisaProdutosListaActionPerformed

    private void btnSairProdutolListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairProdutolListaActionPerformed

        /*Controla a liberação do acesso ao menu cliente*/
        FmPrincipalMdi.Acesso(true);
        setVisible(false);
    }//GEN-LAST:event_btnSairProdutolListaActionPerformed

    private void btnPesquisarNomePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomePActionPerformed

                pesquisaProdutoLista();

        txtPesquisaProdutosLista.setText("");

    }//GEN-LAST:event_btnPesquisarNomePActionPerformed

    public void pesquisaProdutoLista() {

        String sql = "SELECT  * FROM lojaderoupa.produtos WHERE nome like ?";

        try {

            this.stmt = conexao.prepareStatement(sql);
            this.stmt.setString(1, txtPesquisaProdutosLista.getText() + "%");
            this.rs = stmt.executeQuery();
            this.tabListaProdutos.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException u) {
            throw new RuntimeException(u);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarNomeP;
    private javax.swing.JButton btnSairProdutolLista;
    private javax.persistence.EntityManager dblojaPUEntityManager0;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelListarProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<br.com.loja.roupas.view.Produtos> produtosList;
    private java.util.List<br.com.loja.roupas.view.Produtos> produtosList1;
    private java.util.List<br.com.loja.roupas.view.Produtos> produtosList2;
    private java.util.List<br.com.loja.roupas.view.Produtos> produtosList3;
    private javax.persistence.Query produtosQuery;
    private javax.swing.JTable tabListaProdutos;
    private javax.swing.JTextField txtPesquisaProdutosLista;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
